name: My Second Workflow File

on:
  pull_request:
    branches: [main] 
jobs:
  my-job2:
    name: My Job
    runs-on: ubuntu-latest

    steps:
    #Step 1: Check out the source code from the repository
    - name: Check out code
      uses: actions/checkout@v3
      
    #Step 2: print a Greeting message
    - name: Print a greeting 
      run:
        echo "Hello There"
        
    #Step 3: Set up Python (you can specify the version)
    - name: Set up Python
      uses: actions/setup-python@v4

    #Step 4: Install dependencies (if you have a requirements.txt file)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.tx; fi
        pip install pytest-cov
    - name: Training with Pytest
      run: |
        pytest: -v -cov --junitxml=report.xml

    - name: Checkout Hidden Repo
      uses: actions/checkout@v4
      with:
        repository: LimWeiZhe/UOBHidden
        token: ${{ secrets.SECRETUOB }}
        path: hiddenfolder

    - name: print out hidden things
      run: |
        ls
        cd hiddenfolder
        ls
        
    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v2
    #   if: always()
    #   with:
    #     files: |
    #       junit_files: "report.xml"
          
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets."https://discord.com/api/webhooks/1293767681069289502/4eVwiW1wmTOxcqjbv0qPn9rw5lQpfuiLIwrZ13JOW43nayW9FdCxZX6LCRhWFFIH3iyH" }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ LimWeiZhe/uobGitTest.repository.full_name }} has been deployed.'
          
  
